sudo: true
language: python
python: 
  - "3.9"

matrix:
    fast_finish: true

branches:
  only:
    - /main/

install:
  - pip install mkdocs
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pip install mkdocs-material; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then pip install git+https://${GITHUB_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git; fi'
  - pip install mkdocs-git-revision-date-localized-plugin

script:
  - mkdocs build --clean
  
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
