site_name: Islandora
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora/documentation
site_url: https://islandora.github.io/documentation/
edit_uri: 'edit/main/docs/'

theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'assets/Islandora_logo.png'
  language: 'en'
markdown_extensions:
  - admonition
  - footnotes
  - toc:
        permalink: True
extra_css:
  - css/custom.css
plugins:
  - search
  - git-revision-date-localized

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'
  palette:
    primary: 'red'
    accent: 'red'
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/islandora'

copyright: <b>This documentation is user-sourced!</b> Suggestions and comments are welcome in our <u><a href="https://github.com/Islandora/documentation/issues" target="_blank">issue queue</a></u>.

nav:
  - 'About': 'index.md'
  # Conceptual, all user roles: should contain high-level information about
  # what everybody needs to know to understand Islandora and interact with it
  # Possibly add page/section: How to use this documentation (containing user role definitions)
  - Concepts:
      - 'Nodes in Islandora': 'concepts/node-concepts.md'
      - 'Media in Islandora': 'concepts/node-media.md'
      - 'Derivatives': 'concepts/derivatives.md'
      - 'RDF Repository': 'concepts/rdf.md'
  - Behaviours (Models):
      - 'Collections': 'concepts/collection.md'
      - 'Paged Content': 'user-documentation/paged-content.md'
              # conceptual and procedural, repository managers/ curators
              # move out procedural description for ordering pages
      - 'Audio': 'models/audio.md'
      - 'Video': 'models/video.md'
  

  - Installation:
      # Procedural, different user roles: clarify who the audience is for a
      # particular recipe. The ISLE documentation page was written with a
      # 'non-technical' user in mind who wants to test. The Manual installation
      # guides mention that users will need additional knowledge about server administration.
      - 'Release Notes':
          - '8.x-2.0 Release Notes': 'release_notes/8.x-2.0.md'
          - 'Older Release Notes': 'https://github.com/Islandora/documentation/tree/main/docs/release_notes'
      - 'Install a Demo': 'installation/install-a-demo.md'
      - 'Docker (ISLE)':
          - 'Introduction to ISLE': 'installation/docker-introduction.md'
          - 'Prerequisites': 'installation/docker-prereq.md'
          - Install Islandora:
             - 'Installing a Demo Server': 'installation/docker-demo.md'
             - 'Installing a Development Server': 'installation/docker-local.md'
             - 'Installing a Staging/Production Server': 'installation/docker-custom.md'
          - Maintaining Islandora:
            - 'Basic Usage': 'installation/docker-basic-usage.md'
            - 'Maintaining Drupal': 'installation/docker-maintain-drupal.md'
            - 'Maintaining ISLE': 'installation/docker-maintain-isle.md'
          - 'Available Commands': 'installation/docker-available-commands.md'
          - 'Available Configuration': 'installation/docker-available-configuration.md'
          - 'Troubleshooting' : 'installation/docker-troubleshooting.md'
      - 'Ansible Playbook': 'installation/playbook.md'
      - Manual Installation:
        - 'Introduction': 'installation/manual/introduction.md'
        - 'Preparing a LAPP Webserver': 'installation/manual/preparing_a_webserver.md'
        - 'Installing Composer, Drush, and Drupal': 'installation/manual/installing_composer_drush_and_drupal.md'
        - 'Installing Tomcat and Cantaloupe': 'installation/manual/installing_tomcat_and_cantaloupe.md'
        - 'Installing Fedora, Syn, and Blazegraph': 'installation/manual/installing_fedora_syn_and_blazegraph.md'
        - 'Installing Solr': 'installation/manual/installing_solr.md'
        - 'Installing Crayfish': 'installation/manual/installing_crayfish.md'
        - 'Installing Karaf and Alpaca': 'installation/manual/installing_karaf_and_alpaca.md'
        - 'Configuring Drupal': 'installation/manual/configuring_drupal.md'
      - 'Installing Modules': 'technical-documentation/install-enable-drupal-modules.md'
          # procedural, sysadmin
          # moved from System Administrator Documentation
  - Walkthroughs:
      # Audience for this section is someone who is extremely new to doing
      # the kinds of things that we are introducing. This is someone's first
      # foray into this domain so each tutorial should accomplish something
      # satisfying, and work 100% of the time.

      # Tutorials are not conceptual. They tell you exactly what to do without
      # explaining why, and let the user decide if they want to look deeper at
      # what these concepts are.
      - 'Create a Resource Node': 'tutorials/create-a-resource-node.md'
          # procedural, for people learning what islandora is.
      - 'Create a Collection': 'tutorials/how-to-create-collection.md'
          # procedural, repository managers/ curators
      - 'Modify or Create a Content Type': 'user-documentation/content_types.md'
          # procedural, repository managers
          # add resource page on learning YAML
      - 'Configure Blocks': 'tutorials/blocks.md'
          # procedural, repository managers
          # add/link to conceptual documentation about blocks in Drupal?
      - 'Create or Update a View': 'tutorials/create_update_views.md'
          # procedural, repository managers
          # Add/link to conceptual docs about Views?
      - 'Video Documentation': 'user-documentation/video-docs.md'
          # mostly procedural, repository managers
      - 'Create and Manage User Accounts': 'user-documentation/users.md'
          # procedural, repository managers
          # add reference information on user roles that come with Islandora/Islandora Defaults out of the box

  - Using Islandora:
      - 'Introduction': 'user-documentation/user-intro.md'
          # Conceptual, 'site admins/repository managers'
          # move out high-level conceptual information (#architecture section)
      - 'Intro to Linked Data': 'user-documentation/intro-to-ld-for-islandora-8.md'
          # conceptual, repository managers
      - 'Metadata': 'user-documentation/metadata.md'
              # largely conceptual, repository managers/ curators
      - 'Modelling content in Islandora  vs. Legacy': 'user-documentation/objects_to_resource_nodes.md'
              # conceptual, all user roles
              # moved from User documentation > Content in Islandora
      - 'Resource Nodes': 'user-documentation/resource-nodes.md'
            # largely conceptual, repository managers; move out procedural
            # information (e.g. move procedure for setting display hints to
            # documentation about contexts)
      - 'Access Control': 'concepts/access-control.md'
      - 'Accessibility': 'concepts/accessibility.md'
     # conceptual
      - 'Media': 'user-documentation/media.md'
            # conceptual and procedural, repository managers
            # move out procedural description for deleting Media
      - 'Configure Search': 'user-documentation/searching.md'
          # procedural, repository manager
      - 'Add a Facet Block on Vocabulary Reference Field': 'user-documentation/facet_on_vocabulary_reference_fields.md'
          # procedural, repository manager
      - 'Configure Advanced Search': 'user-documentation/advanced-search.md'
          # procedural, repository manager
      - 'Configure Context': 'user-documentation/context.md'
          # conceptual and procedural, repository managers
      - 'Multilingual': 'user-documentation/multilingual.md'
          # conceptual/ procedual/ reference, repository managers
      - 'Extending Islandora': 'user-documentation/extending.md'
          # conceptual, repository managers/ developers
      - 'Viewers': 'user-documentation/file_viewers.md'
          # conceptual, understanding a very complex network of config. For repo managers/devs.
      - 'IIIF': 'user-documentation/iiif.md'
          # conceptual/ procedural, repository managers
          # add reference documentation about IIIF presentation API implementation
      - 'OAI-PMH': 'user-documentation/oai.md'
          # conceptual, repository managers
          # add reference documentation for developers?
      - 'RDF Generation': 'islandora/rdf-mapping.md'
          # conceptual/reference/procedure, repository managers/ developers
      - 'Drupal Bundle Configurations': 'islandora/drupal-bundle-configurations.md'
          # conceptual/procedure, repository managers
      - 'Flysystem': 'technical-documentation/flysystem.md'
          # moved from Developer documentation
      - 'Usage Stats': 'user-documentation/usage-stats.md'
          # largely conceptual, repository managers
      - 'Versioning': 'user-documentation/versioning.md'
          # conceptual/ reference, repository managers/ developers
      - 'JWT Authentication': 'technical-documentation/jwt.md'
          # moved from Developer documentation
      - 'Large files': 'technical-documentation/uploading-large-files.md'
      - Islandora Defaults: 'reference/islandora_defaults_reference.md'
  - Documentation for Developers:
    - 'Stack Overview': 'installation/component_overview.md'
          # moved from "Installation" section; alternatively duplicate a simplified version in the overview section
          # also see Architecture Diagram in Developer documentation
          # also see user-intro.md#architecture for the cheeseburger/bento box analogy
          # Conceptual/ reference, all user roles/ sys admins/ developers:
          # procedural information should be moved out installation guides
    - 'Architecture Diagram': 'technical-documentation/diagram.md'
    - REST Documentation:
      - 'Introduction': 'technical-documentation/using-rest-endpoints.md'
      - 'Authorization': 'technical-documentation/rest-authorization.md'
      - 'GET': 'technical-documentation/rest-get.md'
      - 'POST/PUT': 'technical-documentation/rest-create.md'
      - 'PATCH': 'technical-documentation/rest-patch.md'
      - 'DELETE': 'technical-documentation/rest-delete.md'
      - 'Signposting': 'technical-documentation/rest-signposting.md'
    - Alpaca:
      - 'Alpaca Technical Stack': 'alpaca/alpaca-technical-stack.md'
      - 'Alpaca Tips': 'technical-documentation/alpaca_tips.md'
    - Tests:
      - 'Testing Notes': 'technical-documentation/testing-notes.md'
    - 'Resizing a VM': 'technical-documentation/resizing_vm.md'
    - 'Updating Drupal': 'technical-documentation/updating_drupal.md'
    - 'Updating a `deb` and adding it to Lyrasis PPA': 'technical-documentation/ppa-documentation.md'
    - 'Adding back ?_format=jsonld': 'technical-documentation/adding_format_jsonld.md'
  - Migration:
      - 'Migration Overview': 'technical-documentation/migration-overview.md'
      - 'REST API': 'technical-documentation/migration-rest-api.md'
      - 'Migrate API': 'technical-documentation/migration-migrate-api.md'
      - 'Islandora Workbench': 'technical-documentation/migration-islandora-workbench.md'
      - 'CSV': 'technical-documentation/migrate-csv.md'
      - 'Islandora 7': 'technical-documentation/migrate-7x.md'
  - Contributing:
      - 'How to contribute': 'contributing/CONTRIBUTING.md'
      - 'Running Tests': 'technical-documentation/running-automated-tests.md'
      - 'Checking Coding Standards': 'technical-documentation/checking-coding-standards.md'
      - 'Contributing Workflow': 'contributing/contributing-workflow.md'
      - 'Creating GitHub Issues': 'contributing/create_issues.md'
      - 'Versioning Policy': 'technical-documentation/versioning.md'
      - 'How to release': 'contributing/releasing-islandora.md'
      - 'How to Edit Documentation': 'contributing/editing-docs.md'
      - 'How to Build Documentation': 'technical-documentation/docs-build.md'
          # moved from Developer documentation
      - 'Documentation Style Guide': 'contributing/docs_style_guide.md'
      - 'Committers': 'contributing/committers.md'
  - Glossary: 'user-documentation/glossary.md'
